#!/bin/bash

## -----------------------------------------------------------------------
#  nome do computador
#
HOST=`hostname`

## -----------------------------------------------------------------------
#  diretorio da aplicacao
#
cd ~/SiPAR/atual

## -----------------------------------------------------------------------
#  executa a aplicacao
#
/usr/bin/env python -OO ./controle.py 2> ./controle.$HOST.out

## -----------------------------------------------------------------------
#  diretorio raiz
#
cd ~
