# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgEditPAR.ui'
#
# Created: Wed Sep 22 10:03:12 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_dlgEditPAR(object):
    def setupUi(self, dlgEditPAR):
        dlgEditPAR.setObjectName("dlgEditPAR")
        dlgEditPAR.resize(563, 409)
        dlgEditPAR.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        dlgEditPAR.setSizeGripEnabled(True)
        dlgEditPAR.setModal(True)
        self.formLayout = QtGui.QFormLayout(dlgEditPAR)
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.lblKey = QtGui.QLabel(dlgEditPAR)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblKey.sizePolicy().hasHeightForWidth())
        self.lblKey.setSizePolicy(sizePolicy)
        self.lblKey.setObjectName("lblKey")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblKey)
        self.qleKey = QtGui.QLineEdit(dlgEditPAR)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qleKey.sizePolicy().hasHeightForWidth())
        self.qleKey.setSizePolicy(sizePolicy)
        self.qleKey.setObjectName("qleKey")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.qleKey)
        self.lblDescr = QtGui.QLabel(dlgEditPAR)
        self.lblDescr.setObjectName("lblDescr")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblDescr)
        self.qleDescr = QtGui.QLineEdit(dlgEditPAR)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qleDescr.sizePolicy().hasHeightForWidth())
        self.qleDescr.setSizePolicy(sizePolicy)
        self.qleDescr.setObjectName("qleDescr")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.qleDescr)
        self.lblCab = QtGui.QLabel(dlgEditPAR)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCab.sizePolicy().hasHeightForWidth())
        self.lblCab.setSizePolicy(sizePolicy)
        self.lblCab.setObjectName("lblCab")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblCab)
        self.qsbCab = QtGui.QSpinBox(dlgEditPAR)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qsbCab.sizePolicy().hasHeightForWidth())
        self.qsbCab.setSizePolicy(sizePolicy)
        self.qsbCab.setAlignment(QtCore.Qt.AlignRight)
        self.qsbCab.setSuffix("")
        self.qsbCab.setMinimum(1)
        self.qsbCab.setMaximum(36)
        self.qsbCab.setSingleStep(1)
        self.qsbCab.setProperty("value", 2)
        self.qsbCab.setObjectName("qsbCab")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.qsbCab)
        self.lblHAnt0 = QtGui.QLabel(dlgEditPAR)
        self.lblHAnt0.setObjectName("lblHAnt0")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblHAnt0)
        self.qsbHAnt0 = QtGui.QSpinBox(dlgEditPAR)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qsbHAnt0.sizePolicy().hasHeightForWidth())
        self.qsbHAnt0.setSizePolicy(sizePolicy)
        self.qsbHAnt0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qsbHAnt0.setMinimum(0)
        self.qsbHAnt0.setMaximum(1000)
        self.qsbHAnt0.setSingleStep(10)
        self.qsbHAnt0.setProperty("value", 100)
        self.qsbHAnt0.setObjectName("qsbHAnt0")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.qsbHAnt0)
        self.lblHAnt1 = QtGui.QLabel(dlgEditPAR)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHAnt1.sizePolicy().hasHeightForWidth())
        self.lblHAnt1.setSizePolicy(sizePolicy)
        self.lblHAnt1.setObjectName("lblHAnt1")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.lblHAnt1)
        self.qsbHAnt1 = QtGui.QSpinBox(dlgEditPAR)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qsbHAnt1.sizePolicy().hasHeightForWidth())
        self.qsbHAnt1.setSizePolicy(sizePolicy)
        self.qsbHAnt1.setAlignment(QtCore.Qt.AlignRight)
        self.qsbHAnt1.setMinimum(0)
        self.qsbHAnt1.setMaximum(1000)
        self.qsbHAnt1.setSingleStep(10)
        self.qsbHAnt1.setProperty("value", 100)
        self.qsbHAnt1.setObjectName("qsbHAnt1")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.qsbHAnt1)
        self.lblDstAntEixo = QtGui.QLabel(dlgEditPAR)
        self.lblDstAntEixo.setObjectName("lblDstAntEixo")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.lblDstAntEixo)
        self.qsbDstAntEixo = QtGui.QSpinBox(dlgEditPAR)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qsbDstAntEixo.sizePolicy().hasHeightForWidth())
        self.qsbDstAntEixo.setSizePolicy(sizePolicy)
        self.qsbDstAntEixo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qsbDstAntEixo.setMinimum(0)
        self.qsbDstAntEixo.setMaximum(1000)
        self.qsbDstAntEixo.setSingleStep(10)
        self.qsbDstAntEixo.setProperty("value", 100)
        self.qsbDstAntEixo.setObjectName("qsbDstAntEixo")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.qsbDstAntEixo)
        self.lblDstAntPT0 = QtGui.QLabel(dlgEditPAR)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDstAntPT0.sizePolicy().hasHeightForWidth())
        self.lblDstAntPT0.setSizePolicy(sizePolicy)
        self.lblDstAntPT0.setObjectName("lblDstAntPT0")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.lblDstAntPT0)
        self.qsbDstAntPT0 = QtGui.QSpinBox(dlgEditPAR)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qsbDstAntPT0.sizePolicy().hasHeightForWidth())
        self.qsbDstAntPT0.setSizePolicy(sizePolicy)
        self.qsbDstAntPT0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qsbDstAntPT0.setMinimum(0)
        self.qsbDstAntPT0.setMaximum(1000)
        self.qsbDstAntPT0.setSingleStep(10)
        self.qsbDstAntPT0.setProperty("value", 100)
        self.qsbDstAntPT0.setObjectName("qsbDstAntPT0")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.qsbDstAntPT0)
        self.lblDstAntPT1 = QtGui.QLabel(dlgEditPAR)
        self.lblDstAntPT1.setObjectName("lblDstAntPT1")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.lblDstAntPT1)
        self.qsbDstAntPT1 = QtGui.QSpinBox(dlgEditPAR)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qsbDstAntPT1.sizePolicy().hasHeightForWidth())
        self.qsbDstAntPT1.setSizePolicy(sizePolicy)
        self.qsbDstAntPT1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qsbDstAntPT1.setMaximum(1000)
        self.qsbDstAntPT1.setSingleStep(10)
        self.qsbDstAntPT1.setProperty("value", 100)
        self.qsbDstAntPT1.setObjectName("qsbDstAntPT1")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.qsbDstAntPT1)
        self.lblAngRampa = QtGui.QLabel(dlgEditPAR)
        self.lblAngRampa.setObjectName("lblAngRampa")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.lblAngRampa)
        self.qsbAngRampa = QtGui.QSpinBox(dlgEditPAR)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qsbAngRampa.sizePolicy().hasHeightForWidth())
        self.qsbAngRampa.setSizePolicy(sizePolicy)
        self.qsbAngRampa.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qsbAngRampa.setMaximum(5)
        self.qsbAngRampa.setProperty("value", 1)
        self.qsbAngRampa.setObjectName("qsbAngRampa")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.qsbAngRampa)
        self.lblRetardo = QtGui.QLabel(dlgEditPAR)
        self.lblRetardo.setObjectName("lblRetardo")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.lblRetardo)
        self.qsbRetardo = QtGui.QSpinBox(dlgEditPAR)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qsbRetardo.sizePolicy().hasHeightForWidth())
        self.qsbRetardo.setSizePolicy(sizePolicy)
        self.qsbRetardo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qsbRetardo.setMaximum(10)
        self.qsbRetardo.setProperty("value", 5)
        self.qsbRetardo.setObjectName("qsbRetardo")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.qsbRetardo)
        self.lblDecl = QtGui.QLabel(dlgEditPAR)
        self.lblDecl.setObjectName("lblDecl")
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.lblDecl)
        self.qsbDecl = QtGui.QSpinBox(dlgEditPAR)
        self.qsbDecl.setMinimum(-90)
        self.qsbDecl.setMaximum(90)
        self.qsbDecl.setProperty("value", 10)
        self.qsbDecl.setObjectName("qsbDecl")
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.qsbDecl)
        self.buttonBox = QtGui.QDialogButtonBox(dlgEditPAR)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.buttonBox)
        self.lblKey.setBuddy(self.qleKey)
        self.lblDescr.setBuddy(self.qleDescr)
        self.lblCab.setBuddy(self.qsbCab)
        self.lblHAnt0.setBuddy(self.qsbHAnt0)
        self.lblHAnt1.setBuddy(self.qsbHAnt1)
        self.lblDstAntEixo.setBuddy(self.qsbDstAntEixo)
        self.lblDstAntPT0.setBuddy(self.qsbDstAntPT0)

        self.retranslateUi(dlgEditPAR)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), dlgEditPAR.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), dlgEditPAR.reject)
        QtCore.QMetaObject.connectSlotsByName(dlgEditPAR)
        dlgEditPAR.setTabOrder(self.qleKey, self.qleDescr)
        dlgEditPAR.setTabOrder(self.qleDescr, self.qsbCab)
        dlgEditPAR.setTabOrder(self.qsbCab, self.qsbHAnt0)
        dlgEditPAR.setTabOrder(self.qsbHAnt0, self.qsbHAnt1)
        dlgEditPAR.setTabOrder(self.qsbHAnt1, self.qsbDstAntEixo)
        dlgEditPAR.setTabOrder(self.qsbDstAntEixo, self.qsbDstAntPT0)

    def retranslateUi(self, dlgEditPAR):
        dlgEditPAR.setWindowTitle(QtGui.QApplication.translate("dlgEditPAR", "SiPAR - Edição de Sítio PAR", None, QtGui.QApplication.UnicodeUTF8))
        self.lblKey.setText(QtGui.QApplication.translate("dlgEditPAR", "&Sigla:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDescr.setText(QtGui.QApplication.translate("dlgEditPAR", "Descrição:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCab.setText(QtGui.QApplication.translate("dlgEditPAR", "Cabeceira principal:", None, QtGui.QApplication.UnicodeUTF8))
        self.qsbCab.setSpecialValueText(QtGui.QApplication.translate("dlgEditPAR", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHAnt0.setText(QtGui.QApplication.translate("dlgEditPAR", "Altura da antena relativa ao ponto de toque principal:", None, QtGui.QApplication.UnicodeUTF8))
        self.qsbHAnt0.setSuffix(QtGui.QApplication.translate("dlgEditPAR", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHAnt1.setText(QtGui.QApplication.translate("dlgEditPAR", "Altura da antena relativa ao ponto de toque secundário:", None, QtGui.QApplication.UnicodeUTF8))
        self.qsbHAnt1.setSpecialValueText(QtGui.QApplication.translate("dlgEditPAR", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.qsbHAnt1.setSuffix(QtGui.QApplication.translate("dlgEditPAR", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDstAntEixo.setText(QtGui.QApplication.translate("dlgEditPAR", "Distância da antena ao eixo da pista:", None, QtGui.QApplication.UnicodeUTF8))
        self.qsbDstAntEixo.setSuffix(QtGui.QApplication.translate("dlgEditPAR", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDstAntPT0.setText(QtGui.QApplication.translate("dlgEditPAR", "Distância da antena ao ponto de toque principal:", None, QtGui.QApplication.UnicodeUTF8))
        self.qsbDstAntPT0.setSuffix(QtGui.QApplication.translate("dlgEditPAR", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDstAntPT1.setText(QtGui.QApplication.translate("dlgEditPAR", "Distância da antena ao ponto de toque secundário:", None, QtGui.QApplication.UnicodeUTF8))
        self.qsbDstAntPT1.setSuffix(QtGui.QApplication.translate("dlgEditPAR", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAngRampa.setText(QtGui.QApplication.translate("dlgEditPAR", "Ângulo da rampa de aproximação:", None, QtGui.QApplication.UnicodeUTF8))
        self.qsbAngRampa.setSuffix(QtGui.QApplication.translate("dlgEditPAR", " gr", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRetardo.setText(QtGui.QApplication.translate("dlgEditPAR", "Retardos:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDecl.setText(QtGui.QApplication.translate("dlgEditPAR", "Declinação magnética do sítio:", None, QtGui.QApplication.UnicodeUTF8))
        self.qsbDecl.setSuffix(QtGui.QApplication.translate("dlgEditPAR", " gr", None, QtGui.QApplication.UnicodeUTF8))

